[package]

name = "errno"
version = "0.1.5"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://lambda.xyz/rust-errno/doc/errno/"
repository = "https://github.com/lfairy/rust-errno"
description = """
Cross-platform interface to the `errno` variable.
"""

[dependencies]
libc = "*"
winapi = "*"
kernel32-sys = "0.2"
